#pragma once

enum MAPMESH_TAG
{
	MAPMESH_TAG_CEILING_DEFAULT,
	MAPMESH_TAG_CEILING_BROKEN,
	MAPMESH_TAG_CEILING_NORMAL,
	MAPMESH_TAG_WALL_WORN,
	MAPMESH_TAG_PILLAR_DEFAULT,
	MAPMESH_TAG_PILLAR_FULL,
	MAPMESH_TAG_FLOOR_DEFAULT,
	MAPMESH_TAG_CONCAVE_WORN,
	MAPMESH_TAG_CORNER_CONCAVE_WORN,
	MAPMESH_TAG_CORNER_CONVER_SHORT,
};

class cMapMesh
{
private:
	LPD3DXMESH			m_pMesh;
	LPDIRECT3DTEXTURE9	m_pTexture;
public:
	cMapMesh();
	~cMapMesh();

	void Setup(int tag);
	void Render(D3DXVECTOR3 pos, D3DXVECTOR3 rot, D3DXVECTOR3 scl);
private:
	LPD3DXMESH LoadMesh(string fileName);
	LPDIRECT3DTEXTURE9 LoadTexture(string fileName);
};